export default {slideActions:[
	{turned: false,
		fixed: false,
		value: 1	},
	{turned: false,
		fixed: false,
		value: 2	},
	{turned: false,
		fixed: false,
		value: 4	},
	{turned: false,
		fixed: false,
		value: 3	},
	{turned: false,
		fixed: false,
		value: 5	},
	{turned: false,
		fixed: false,
		value: 3	},
	{turned: false,
		fixed: false,
		value: 6	},
	{turned: false,
		fixed: false,
		value: 5	},
	{turned: false,
		fixed: false,
		value: 2	},
	{turned: false,
		fixed: false,
		value: 6	},
	{turned: false,
		fixed: false,
		value: 4	},
	{turned: false,
		fixed: false,
		value: 1	},
]}
